### ISSUE TITLE
Mailchimp & Mandrill 세팅

### ISSUE THREAD

**Issue by hoony-o-1** [codeforseoul/congress-report#2]
- Integration: http://kb.mailchimp.com/integrations/other-integrations/mandrill-for-mailchimp-users
- Using Handlebars: https://mandrill.zendesk.com/hc/en-us/articles/205582537
- Mailer API: https://mandrillapp.com/api/docs/messages.python.html

이 세가지 링크를 참조하셔서 `mailer.py` 코드 한번 살펴보시고 템플릿 안에 handlerbar 문법 적용해서 템플릿 커스터마이징 한번 해보세요! 그 이후에는 디자인이 나와야 주희님 작업할 파트가 생길 것 같네요 :) :+1:

**Comment by JH27** [comment]
[이렇게](https://codeforseoul.slack.com/files/joohee/F0A8GRXK7/__________py.py) 한
